#!/bin/bash

echo "Force Installing Surge XT S&S Fork v2.5.0..."
echo ""
echo "Step 1: Removing old installation..."
sudo rm -rf "/Library/Audio/Plug-Ins/VST3/Surge XT.vst3"
sudo rm -rf "/Library/Audio/Plug-Ins/VST3/Surge XT.vst3.backup"

echo "Step 2: Copying new build..."
sudo cp -R "build-arm64/surge_xt_products/Surge XT.vst3" "/Library/Audio/Plug-Ins/VST3/"

echo "Step 3: Setting permissions..."
sudo chmod -R 755 "/Library/Audio/Plug-Ins/VST3/Surge XT.vst3"
sudo xattr -cr "/Library/Audio/Plug-Ins/VST3/Surge XT.vst3"

echo "Step 4: Verifying installation..."
if strings "/Library/Audio/Plug-Ins/VST3/Surge XT.vst3/Contents/MacOS/Surge XT" | grep -q "S&S Fork v2.5.0"; then
    echo "✅ SUCCESS: S&S Fork v2.5.0 installed correctly!"
    echo ""
    echo "Installed file info:"
    ls -la "/Library/Audio/Plug-Ins/VST3/Surge XT.vst3/Contents/MacOS/Surge XT"
    echo ""
    echo "🎯 CRITICAL FIX IN v2.5.0: VST PARAMETERS NOW ACCESSIBLE!"
    echo ""
    echo "WHAT WAS WRONG:"
    echo "• Parameters 900-903 weren't registered with JUCE/VST3"
    echo "• REAPER couldn't see them - got errors when trying to read"
    echo "• Both instances paired to same track due to missing signatures"
    echo ""
    echo "WHAT'S FIXED:"
    echo "• Created SurgeSignatureParameter class in JUCE wrapper"
    echo "• Properly registered 4 signature parameters with VST3"
    echo "• Parameters now accessible via TrackFX_GetParam()"
    echo "• Each instance exposes its unique signature"
    echo ""
    echo "HOW IT WORKS NOW:"
    echo "1. Each Surge instance has unique signature (PID-Instance-Hash)"
    echo "2. Signature split into 4 parts, exposed as VST params"
    echo "3. Assistant reads params via TrackFX_GetParam(track, fx, 900-903)"
    echo "4. Reconstructs full signature"
    echo "5. Matches with broker registration"
    echo "6. Routes commands to correct instance on correct track!"
    echo ""
    echo "TEST IN REAPER:"
    echo "local track = reaper.GetTrack(0, 0)"
    echo "for i = 900, 903 do"
    echo "    local val = reaper.TrackFX_GetParam(track, 0, i)"
    echo "    print(string.format('Param %d: %08X', i, math.floor(val * 0xFFFFFFFF)))"
    echo "end"
    echo ""
    echo "This should fix the multi-instance routing problem!"
else
    echo "❌ ERROR: Installation verification failed!"
fi