#!/bin/bash

echo "Force Installing Surge XT S&S Fork v2.4.0..."
echo ""
echo "Step 1: Removing old installation..."
sudo rm -rf "/Library/Audio/Plug-Ins/VST3/Surge XT.vst3"
sudo rm -rf "/Library/Audio/Plug-Ins/VST3/Surge XT.vst3.backup"

echo "Step 2: Copying new build..."
sudo cp -R "build-arm64/surge_xt_products/Surge XT.vst3" "/Library/Audio/Plug-Ins/VST3/"

echo "Step 3: Setting permissions..."
sudo chmod -R 755 "/Library/Audio/Plug-Ins/VST3/Surge XT.vst3"
sudo xattr -cr "/Library/Audio/Plug-Ins/VST3/Surge XT.vst3"

echo "Step 4: Verifying installation..."
if strings "/Library/Audio/Plug-Ins/VST3/Surge XT.vst3/Contents/MacOS/Surge XT" | grep -q "S&S Fork v2.4.0"; then
    echo "✅ SUCCESS: S&S Fork v2.4.0 installed correctly!"
    echo ""
    echo "Installed file info:"
    ls -la "/Library/Audio/Plug-Ins/VST3/Surge XT.vst3/Contents/MacOS/Surge XT"
    echo ""
    echo "🔑 CRITICAL FEATURE IN v2.4.0: PLUGIN SIGNATURE PARAMETERS"
    echo ""
    echo "HIDDEN VST PARAMETERS:"
    echo "• Parameter 900: Plugin Signature Part 0 (PID)"
    echo "• Parameter 901: Plugin Signature Part 1 (Instance)"  
    echo "• Parameter 902: Plugin Signature Part 2 (Hash High)"
    echo "• Parameter 903: Plugin Signature Part 3 (Hash Low)"
    echo ""
    echo "HOW IT WORKS:"
    echo "1. Surge generates unique 128-bit signature on startup"
    echo "2. Signature is split into 4x 32-bit parts"
    echo "3. Parts exposed as hidden VST parameters 900-903"
    echo "4. Assistant reads via TrackFX_GetParam(track, fx, 900-903)"
    echo "5. Reconstructs full signature to match with broker registration"
    echo ""
    echo "BENEFITS:"
    echo "• Works within VST3 sandbox restrictions"
    echo "• No socket communication needed from plugin"
    echo "• REAPER can easily read these parameters"
    echo "• Signature matches broker registration exactly"
    echo ""
    echo "TEST IN REAPER:"
    echo "ReaScript: val = reaper.TrackFX_GetParam(track, 0, 900)"
    echo "This returns the first part of the plugin signature!"
    echo ""
    echo "The broker system can now correctly match and route to specific instances!"
else
    echo "❌ ERROR: Installation verification failed!"
fi